# Generated by Django 4.2.5 on 2024-03-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userconfirmation_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("verification_code", models.CharField(blank=True, max_length=5)),
                ("email_verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="UserConfirmation",
        ),
    ]
