# Generated by Django 4.2.6 on 2023-10-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_tag_alter_review_product_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(related_name='product_tags', to='movie.tag'),
        ),
    ]
