# Generated by Django 4.2.6 on 2023-10-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='movie.tag'),
        ),
    ]
