# Generated by Django 4.2.5 on 2024-03-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0007_rename_tag_product_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("duration", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="review",
            name="product",
        ),
        migrations.RenameModel(
            old_name="Category",
            new_name="Director",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to="movie.director",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="tags",
            field=models.ManyToManyField(to="movie.tag"),
        ),
        migrations.AddField(
            model_name="review",
            name="movie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="movie.movie",
            ),
            preserve_default=False,
        ),
    ]
